services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blog
      - admin
      - logs
    networks:
      - blog_network
      - admin_logs_network

  blog:
    image: eddx/ctf-govware-blog:latest
    build: ./blog
    networks:
      - blog_network
      - admin_logs_network

  admin:
    image: eddx/ctf-govware-admin:latest
    build: ./admin
    networks:
      - admin_logs_network
      - blog_network

  logs:
    image: eddx/ctf-govware-logs:latest
    build: ./logs
    networks:
      - admin_logs_network

networks:
  blog_network:
    driver: bridge
  admin_logs_network:
    driver: bridge